# Generated by Django 4.2 on 2023-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='sectores_mapa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
