# Generated by Django 4.2 on 2023-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_transporte_sectores_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='sectores_mapa',
        ),
        migrations.AddField(
            model_name='transporte',
            name='url_mapa',
            field=models.URLField(blank=True, null=True),
        ),
    ]
